spring:
  profiles:
    active: local
  batch:
    job:
      #      enabled: false
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  config:
    activate:
      on-profile: mysql
  batch:
    #    job:
    #      names: ${job.name:NONE} # --job.name=batchJob1 name=user1 ㅇㅣ런설정을하면 batchJob1이 들어감
    #      enabled: false # job 자동  실행 막음.
    jdbc:
      initialize-schema: always
  #      table-prefix:  # table prefix
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?userUnicode=true&characterEncoding=utf8
      username: root
      password: wnstjd94
      driver-class-name: com.mysql.cj.jdbc.Driver




---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/springbatch #;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always